name: webapp
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: build
        run: dotnet build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: test
        run: dotnet test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: deploy
        run: echo "deploying"

  build_after_approval:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: build
        run: dotnet build

  manual-approval:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Manual Approval
        uses: actions/github-script@v4
        with:
          script: |
            const { data: approvals } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const approvedReviewers = approvals.filter(approval => approval.state === 'APPROVED').map(approval => approval.user.login);

            if (approvedReviewers.length >= 2) {
              console.log('The required number of approvals is met.');
              return { approved: true };
            } else {
              console.log('Waiting for approvals. Current approvals:', approvedReviewers.length);
              return { approved: false };
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_after_approval:
    runs-on: ubuntu-latest
    needs: [manual-approval, build_after_approval]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: test
        run: dotnet test

  deploy_after_approval:
    runs-on: ubuntu-latest
    needs: test_after_approval
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: deploy
        run: echo "deploying"
